version: '3.8'
services:
  database: 
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
    ports:
      - 8765:5432
    environment:
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_USER: 'user'
      POSTGRES_DB: 'db'